name: Deploy Locally

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Runs on your Ubuntu machine inside the Tailscale network

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Deployment Command
        run: echo "it works" > ~/test_output.txt